# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iOSfoodDeliveryApp', '0004_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
